- lib/Digitick/Sepa/DomBuilder/CustomerCreditTransferDomBuilder.php
- lib/Digitick/Sepa/TransferFile/Facade/CustomerCreditFacade.php
- lib/Digitick/Sepa/TransferFile/Factory/TransferFileFacadeFactory.php
- lib/Digitick/Sepa/TransferInformation/BaseTransferInformation.php
- tests/CustomerCreditFacadeTest.php
- tests/CustomerCreditValidationTest.php
- tests/pain.001.003.03.xml
- tests/pain.001.003.03.xsd
This should fix #14 and make the `TransferFileFacadeFactory` completely usable. I also updated the format within this change to `pain.001.003.03` and uploaded the new schemas for this format.
> Add: Missing CustomerCreditFacade

- tests/CustomerCreditValidationPain00100103Test.php
- tests/CustomerCreditValidationTest.php
- tests/CustomerDirectDebitFacadeTest.php
- tests/CustomerDirectDebitValidationTest.php
This is only to verify that we do not break BC in any future release with all currently used `pain` formats and variants. This does not go down to the very first version of all variants but starts with those versions which are used in the method definitions.
> Tests for all schemas

- lib/Digitick/Sepa/TransferInformation/BaseTransferInformation.php
- tests/Unit/SumOutputTest.php
bcmul() function expects [two strings](http://php.net/manual/en/function.bcmul.php#refsect1-function.bcmul-parameters) but BaseTransferInformation constructor uses a float and an integer. This usage converts float values with decimals into zeros depending on locale configuration, so each transfer is added with zero amount.
This behaviour is not clearly documented in PHP, but bcmul() an other BC Math functions casts parameters to strings returning inaccurate or directly wrong results without showing errors or throwing exceptions.
You can test with this code on Linux:
```
setlocale(LC_ALL, 'es_ES.UTF-8');
var_dump(bcmul(143.50, 100, 2));
setlocale(LC_ALL, 'C');
var_dump(bcmul(143.50, 100, 2));
```
Result:
```
string '0' (length=1)
string '14350.0' (length=7)
```
This can be solved using …
> Fixed amounts with decimals

- doc/direct_credit.md
- doc/direct_debit.md
- lib/Digitick/Sepa/DomBuilder/CustomerDirectDebitTransferDomBuilder.php
- lib/Digitick/Sepa/TransferFile/Facade/CustomerDirectDebitFacade.php
- lib/Digitick/Sepa/TransferInformation/CustomerDirectDebitTransferInformation.php
- tests/Unit/Digitick/Sepa/TransferInformation/CustomerDirectDebitTransferInformationTest.php
> In the previous versions of the Guidelines, the acronym ‘SMNDA’ was used to indicate
Same Mandate with a New Debtor Agent. However, when the Creditor only receives the
IBAN it will not always be possible to derive if an account change took place in the same or
in another bank. To better accommodate this situation, the definition of the acronym
‘SMNDA’ has been updated to indicate Same Mandate with a New Debtor Account.
Source: http://www.europeanpaymentscouncil.eu/index.cfm/knowledge-bank/epc-documents/sepa-direct-debit-core-scheme-customer-to-bank-implementation-guidelines-version-90/epc130-08-sdd-core-c2b-ig-v90-approvedpdf/ (Section 1.5.4)
This PR updates the way amendments are added to the SEPA file to comply with the most recent direct debit rulebook (version 9). Readme and tests …
> Update amendments with compliance to SDD Rulebook v9

- lib/Digitick/Sepa/DomBuilder/CustomerCreditTransferDomBuilder.php
- tests/CustomerCreditValidationTest.php
An empty <Ustrd/> element is invalid according PAIN specification.
I've added a test that fails without the fix provided.
> Don't add RemittanceElement when there is no RemittanceInformation

- lib/Digitick/Sepa/DomBuilder/CustomerCreditTransferDomBuilder.php
- lib/Digitick/Sepa/GroupHeader.php
- lib/Digitick/Sepa/PaymentInformation.php
Add get/setters for organization id and identification scheme in both PaymentInformation and GroupHeader.
Nordea Finland requires identification scheme code with organization id to work. Resulting XML passes Nordea XML validator.
> Setters for organization id and identification scheme

- .travis.yml
- doc/direct_debit.md
Since I just implemented the library yesterday and had a bit of a slow start, I am submitting some improvements to the readme:
- Supplying endToEndId and making comment that it is optional
- Supplying dueDate with now +7 days, since this is usually the default by consumer law (at least in DE)
- exposing CORE default
- Gave initiating variables a clearer name 
- Using pain.008.003.02 in example. With our bank this was the preferred schema. I was not quite clear, why you still supply the old as default? 
I hope these improvements make sense, as I think that the use-case of making a direct debit IRL more often includes these params than it would omit them. Therefore it makes sense to include them in the "getting started" Readme.
> Readme improvements

- lib/Digitick/Sepa/DomBuilder/CustomerCreditTransferDomBuilder.php
- lib/Digitick/Sepa/DomBuilder/CustomerDirectDebitTransferDomBuilder.php
- lib/Digitick/Sepa/PaymentInformation.php
- tests/CustomerCreditValidationTest.php
- tests/CustomerDirectDebitValidationTest.php
Hi and thanks for this library :cat: I would like to set `instruction priority` in `payment type information` as defined eg. [here](https://github.com/php-sepa-xml/php-sepa-xml/blob/8f9814bc7c97eda669e93848df3dcdb28ca7debb/tests/pain.001.001.03.xsd#L669). Could you please have a look on this pull request? Thanks for your time.
> Add instruction priority to payment information

- lib/Digitick/Sepa/DomBuilder/CustomerCreditTransferDomBuilder.php
- tests/CustomerCreditValidationTest.php
* Allows for creditor address in credit transfer, needed when doing transfers with foreign currencies.
* Add test for different address combinations.
> Add unstructured creditor address to credit transfer xml.

- lib/Digitick/Sepa/TransferFile/BaseTransferFile.php
The validate function return an error because count($this->paymentInformations) can be done if there is no paymentInformations.
> Init $paymentInformations value

- doc/direct_credit.md
- doc/direct_debit.md
- src/TransferFile/Facade/CustomerCreditFacade.php
Pull request has following changes
* Add option for batch booking for credit transfer, previously this option was available only for debit transfer but with this pull request, we can set `batch booking` for credit transfer as well.
* Update doc (mention that amount is in cents)
> add batch booking option for credit transfer

- CHANGELOG.md
- doc/direct_credit.md
- doc/direct_debit.md
- src/TransferFile/Facade/CustomerCreditFacade.php
The example markdown shows the availablity of ->setBatchBooking() in the credit and debit facade, but this method is not callable in $customerCredit/directDebit Facade, only if you assign the PaymentInformation  instance, returned by addPaymentInfo().
> Fix documentation

- src/DomBuilder/CustomerDirectDebitTransferDomBuilder.php
For Belgian banks the issuer of the organisation id must be present.
> Add issuer for Belgian banks

- src/DomBuilder/CustomerDirectDebitTransferDomBuilder.php
PHP 8.1 throws a deprecation warning if null is passed to strlen function.
A cast to string solves this issue.
It would also be possible to check for null instead of casting right before the function call of strlen.
> PHP 8.1 deprecation warning

- src/DomBuilder/CustomerCreditTransferDomBuilder.php
PHP 8.1 throws a deprecation warning if null is passed to strlen function.
A cast to string solves this issue.
It would also be possible to check for null instead of casting right before the function call of strlen.
> PHP 8.1 deprecation warning in visitTransferInformation

- src/Util/StringHelper.php
Added apostrophe to StringHelper.php as per the Extended Character Set standard. 
For reference: [SEPA REQUIREMENTS FOR AN EXTENDED CHARACTER SET](https://www.europeanpaymentscouncil.eu/sites/default/files/KB/files/EPC217-08%20Draft%20Best%20Practices%20SEPA%20Requirements%20for%20Character%20Set%20v1.1.pdf)
> Add apostrophe to StringHelper.php as per the Extended Character Set

- .github/workflows/phpstan.yml
- .github/workflows/phpunit.yml
- .github/workflows/rectorci.yml
- README.md
- phpstan.dist.neon
- rector.php
Migrate to GitHub Actions in order to:
- Run PHPUnit
- Run PHPStan
- Run rector with auto-commit
- phpunit workflow
- phpstan workflow
- rectorci workflow
phpstan and rectorci intentionally point to the "testing" branch for now as we need to clean parts of the code before enabling them.
- Travis CI badge
Replaced it with a GH Actions badge and removed the old webhook to it.
There are a few more things to fixup for e.g. the badge needs to be re-created on this repository. I will take care of them when merging.
> Migrate CI to GitHub Actions

- doc/direct_debit.md
- doc/string_sanitization.md
- src/GroupHeader.php
- src/PaymentInformation.php
- src/TransferInformation/BaseTransferInformation.php
- src/TransferInformation/CustomerDirectDebitTransferInformation.php
- src/Util/Sanitizer.php
- tests/Unit/Util/SanitizerTest.php
Hi guys,
I'm currently working on integrating this package with our banking system and needed the generated XML to exactly match the format our bank expects. I had to implement a few changes that I believe could also benefit others using the package.
Currently, string sanitization in the package replaces special characters like ü, &, etc. — for example, `Jürgen & Sohn` becomes `Juergen   Sohn`. However, in many cases, XML entity escaping is sufficient, and users might want to preserve the original characters or apply a custom transformation instead (like setting `&` to `and` or `und` or `y`).
To support this, I added the ability to override the default string sanitization logic globally via a static method
This makes it easier to:
- Disable sanitization entirely with disableSanitizer()
- …
> Allow custom sanitization of strings.

- src/TransferFile/Facade/CustomerCreditFacade.php
In #186, the `$paymentInformation['id']` field's type was changed from `string` to `int`. I believe this was an accident, given that all methods that this value is being passed to accepts strings. Ultimately, the value is used in the `<PmtInfId>` element, which is not documented to be an integer.
> Allow id in $paymentInformation to be a string

- src/TransferFile/Facade/CustomerDirectDebitFacade.php
The façade method `CustomerDirectDebitFacade::addTransfer()` documents the `$transferInformation['debtorAdrLine']` field as `string`. However, the value is passed to `CustomerDirectDebitTransferInformation::setPostalAddress()` which can also handle an array of strings. I'd like to widen the type of the array shape to reflect that.
> Allow debtorAdrLine in `$transferInformation` to be an array
